# ── Setup helpers ────────────────────────────────────────────────────────────
.PHONY: init reset env secrets _init_warmup _post_init_menu

env:            ## Create .env from template if it does not exist yet
	@test -f docker/.env && echo ".env already exists, skipping." || (cp docker/.env.example docker/.env && echo "Created .env – edit host paths if needed.")

secrets:        ## Create docker/docker-compose.secrets.yml from example and secrets/ dir
	@mkdir -p secrets
	@test -f docker/docker-compose.secrets.yml \
		&& echo "docker/docker-compose.secrets.yml already exists, skipping." \
		|| (cp docker/docker-compose.secrets.yml.example docker/docker-compose.secrets.yml \
		    && echo "Created docker/docker-compose.secrets.yml – edit to select your secrets.")
	@echo "Put each API key into its own file under secrets/ (chmod 600)."
	@echo "Example:  echo -n 'sk-ant-…' > secrets/anthropic_api_key.txt && chmod 600 secrets/anthropic_api_key.txt"

reset:          ## Remove all files/dirs generated by  make init  (asks for confirmation)
	@echo ""
	@echo "The following items will be permanently deleted:"
	@echo ""
	@ITEMS=""; \
	 [ -f docker/.env ]                        && ITEMS="$$ITEMS docker/.env"; \
	 [ -f docker/docker-compose.secrets.yml ]  && ITEMS="$$ITEMS docker/docker-compose.secrets.yml"; \
	 [ -d secrets ]                            && ITEMS="$$ITEMS secrets"; \
	 [ -d workspace ]                          && ITEMS="$$ITEMS workspace"; \
	 if [ -z "$$ITEMS" ]; then \
	   echo "  (nothing to remove – already clean)"; echo ""; exit 0; \
	 fi; \
	 for ITEM in $$ITEMS; do \
	   if [ -d "$$ITEM" ]; then \
	     find "$$ITEM" | sed -e "s|[^/]*/|  |g" -e "s|  \([^/]*\)$$|  └─ \1|"; \
	   else \
	     echo "  └─ $$ITEM"; \
	   fi; \
	 done; \
	 echo ""; \
	 printf "  Also remove Docker image  spectagent:latest ? [yes/no] → "; \
	 read REMOVE_IMAGE; \
	 echo ""; \
	 printf "Delete all of the above? [yes/no] → "; \
	 read CONFIRM; \
	 if [ "$$CONFIRM" != "yes" ] && [ "$$CONFIRM" != "y" ] && [ "$$CONFIRM" != "YES" ] && [ "$$CONFIRM" != "Y" ]; then \
	   echo "Aborted. Nothing was deleted."; exit 0; \
	 fi; \
	 $(COMPOSE) down 2>/dev/null || true; \
	 for ITEM in $$ITEMS; do \
	   rm -rf "$$ITEM" && echo "  ✓  Removed $$ITEM"; \
	 done; \
	 case "$$REMOVE_IMAGE" in yes|y|YES|Y) \
	   docker rmi spectagent:latest 2>/dev/null && echo "  ✓  Removed Docker image spectagent:latest" \
	   || echo "  ·  Image spectagent:latest not found, skipping."; \
	 esac; \
	 echo ""; \
	 echo "  Reset complete."

init: env secrets          ## Full first-time setup: env, secrets, build
	@mkdir -p workspace
	@$(MAKE) build
	@$(MAKE) _init_warmup
	@$(MAKE) _post_init_menu

_init_warmup:              ## (internal) first container start – completes workspace init (specify, etc.)
	@echo ""
	@echo "  → Finishing workspace initialisation …"
	@$(COMPOSE) run --rm $(SERVICE) true 2>&1 | sed 's/^/    /'
	@echo "  ✓  Workspace ready."

_post_init_menu:           ## (internal) post-init setup menu
	@echo ""
	@echo "  ✓  Image built successfully."
	@echo ""
	@echo "  Recommended setup steps – pick one to run now, or exit and run later:"
	@echo ""
	@echo "    1)  omo-install  – Install oh-my-opencode & configure AI providers"
	@echo "    2)  omo-auth     – Authenticate with your AI provider (if omo-install already done)"
	@echo "    3)  shell        – Open a bash shell to configure manually"
	@echo "    0)  exit         – Do nothing, return to your terminal"
	@echo ""
	@printf "  Enter choice [0-3]: "; \
	read CHOICE; \
	echo ""; \
	case "$$CHOICE" in \
	  1) $(MAKE) omo-install ;; \
	  2) $(MAKE) omo-auth ;; \
	  3) $(MAKE) shell ;; \
	  0|"") echo "  Run  make <target>  whenever you are ready." ;; \
	  *) echo "  Unknown choice '$$CHOICE'. Run  make <target>  to continue." ;; \
	esac

