# ── Setup helpers ────────────────────────────────────────────────────────────
.PHONY: init reset env secrets

env:            ## Create .env from template if it does not exist yet
	@test -f docker/.env && echo ".env already exists, skipping." || (cp docker/.env.example docker/.env && echo "Created .env – edit host paths if needed.")

secrets:        ## Create docker/docker-compose.secrets.yml from example and secrets/ dir
	@mkdir -p secrets
	@test -f docker/docker-compose.secrets.yml \
		&& echo "docker/docker-compose.secrets.yml already exists, skipping." \
		|| (cp docker/docker-compose.secrets.yml.example docker/docker-compose.secrets.yml \
		    && echo "Created docker/docker-compose.secrets.yml – edit to select your secrets.")
	@echo "Put each API key into its own file under secrets/ (chmod 600)."
	@echo "Example:  echo -n 'sk-ant-…' > secrets/anthropic_api_key.txt && chmod 600 secrets/anthropic_api_key.txt"

reset:          ## Remove all files/dirs generated by  make init  (asks for confirmation)
	@echo ""
	@echo "The following items will be permanently deleted:"
	@echo ""
	@ITEMS=""; \
	 [ -f docker/.env ]                        && ITEMS="$$ITEMS docker/.env"; \
	 [ -f docker/docker-compose.secrets.yml ]  && ITEMS="$$ITEMS docker/docker-compose.secrets.yml"; \
	 [ -d secrets ]                            && ITEMS="$$ITEMS secrets"; \
	 [ -d workspace ]                          && ITEMS="$$ITEMS workspace"; \
	 if [ -z "$$ITEMS" ]; then \
	   echo "  (nothing to remove – already clean)"; echo ""; exit 0; \
	 fi; \
	 for ITEM in $$ITEMS; do \
	   if [ -d "$$ITEM" ]; then \
	     find "$$ITEM" | sed -e "s|[^/]*/|  |g" -e "s|  \([^/]*\)$$|  └─ \1|"; \
	   else \
	     echo "  └─ $$ITEM"; \
	   fi; \
	 done; \
	 echo ""; \
	 printf "  Also remove Docker image  spectagent:latest ? [yes/no] → "; \
	 read REMOVE_IMAGE; \
	 echo ""; \
	 printf "Delete all of the above? [yes/no] → "; \
	 read CONFIRM; \
	 if [ "$$CONFIRM" != "yes" ] && [ "$$CONFIRM" != "y" ] && [ "$$CONFIRM" != "YES" ] && [ "$$CONFIRM" != "Y" ]; then \
	   echo "Aborted. Nothing was deleted."; exit 0; \
	 fi; \
	 $(COMPOSE) down 2>/dev/null || true; \
	 for ITEM in $$ITEMS; do \
	   rm -rf "$$ITEM" && echo "  ✓  Removed $$ITEM"; \
	 done; \
	 case "$$REMOVE_IMAGE" in yes|y|YES|Y) \
	   docker rmi spectagent:latest 2>/dev/null && echo "  ✓  Removed Docker image spectagent:latest" \
	   || echo "  ·  Image spectagent:latest not found, skipping."; \
	 esac; \
	 echo ""; \
	 echo "  Reset complete."

init: env secrets          ## Full first-time setup: env, secrets, build
	@mkdir -p workspace
	@$(MAKE) build
	@echo ""
	@echo "  ✓  Image built. Run  make shell  (or any tool target) to start a container."

